name: telegram_analytics
version: "1.0"
config-version: 2

profile: test_db

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  telegram_analytics:
    +materialized: view
