version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"
    columns:
      - name: channel_id
        tests:
          - not_null
          - unique
      - name: total_messages
        tests:
          - not_null
          - relationships:
              to: ref('fct_messages')
              field: channel_id
              count: "> 0"

  - name: dim_dates
    description: "Date dimension with Ethiopian holidays"
    columns:
      - name: date_id
        tests:
          - not_null
          - unique

  - name: fct_messages
    description: "Fact table for Telegram messages"
    columns:
      - name: message_key
        tests:
          - not_null
          - unique
      - name: channel_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_id
      - name: date_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_id
      - name: mentions_medical
        tests:
          - accepted_values:
              values: [0, 1]