name: CI Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flake8 linting
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || true

      - name: Run tests with pytest
        run: |
          pytest tests/ || true
